"""
Django settings for ProyectoDjangoDash project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a5o_en-qku=s998osgfe72(1#m3%%e@nqe(-9lndggy+7ya%v-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProyectoDjangoDash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoDjangoDash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
#(Venimos de casi abajo del todo del archivo, de los "STATIC")
#Hemos comentado la línea de arriba. Tras : (venv) C:\Users\alaza\ProyectoDjangoDash>pip install psycopg2-binary (en cmd de windos), pegamos abajo...
#... y metemos la BBDD creada previamente en Postgre  
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Dash',
        'USER': 'postgres',
        'PASSWORD': ',pinTo2crieis',
        'HOST': 'localhost'
    }
}
# Luego: (venv) C:\Users\alaza\ProyectoDjangoDash>python manage.py makemigrations
#(venv) C:\Users\alaza\ProyectoDjangoDash>python manage.py migrate
# luego: (venv) C:\Users\alaza\ProyectoDjangoDash>python manage.py collectstatic PARA CREAR UNA CARPETA ESTATICA PRINCIPAL DENTRO DE NUESTRA APLICACION PRINCIPAL
#(para la aplicación de producción) - Con esto python administra que py recopile de forma estática, copiándose 165 archivos estáticos a esta ruta...
#... Y VAMOS A : carpeta templates - index.html: ¡a divertirnos!!!!!! (19:27)

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

#Desde comentarios en base.html (12:22) - Creamos:
STATICFILES_LOCATION='static'

STATIC_URL = '/static/'
#Desde comentarios en base.html (12:22) - Creamos(TAMBIEN):
STATIC_ROOT='static'
#Metemos también:
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'ProyectoDjangoDash/static')
]
# Y nos vamos a DATABASES (más arriba)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
